name: Deploy Discord Bot

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.BOT_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to bot host
      run: |
        ssh -i ~/.ssh/id_ed25519 user@${{ secrets.BOT_HOST }} << 'EOF'
          cd akagi-bot
          git pull origin main
          sudo systemctl restart akagi-bot.service
        EOF
